global:
  scrape_interval: 30s
  evaluation_interval: 30s
scrape_configs:
- job_name: 'node_exporter_10_1_1_1'
  static_configs:
    - targets: ['10.1.1.1:9100']
- job_name: 'node_exporter_10_2_2_2'
  static_configs:
    - targets: ['10.2.2.2:9100']
- job_name: 'node_exporter_10_3_3_3'
  static_configs:
    - targets: ['10.3.3.3:9100']

