[tool.black]
line-length = 120
target-version = ['py39']

[tool.isort]
profile = "black"
line_length = 120
skip = ["__init__.py", ".venv", "build", "dist"]
known_first_party = ["myproject", "anothermodule"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.flake8]
max-line-length = 120
exclude = [
    '.git',
    '__pycache__',
    'build',
    'dist'
]
ignore = ['E203', 'E266', 'E501', 'W503']
per-file-ignores = [
    '__init__.py: F401'
]

[tool.pytest.ini_options]
pythonpath = [
    "."
]