version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"      # LocalStack Edge Proxy
    environment:
      - SERVICES=s3,efs,ssm,ses,lambda,logs,iam
      - DEFAULT_REGION=us-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/tmp/localstack

  arxiv-processor:
    build:
      context: ../services/arxiv_processor
      dockerfile: Dockerfile
    profiles: ["processor", "all"]
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-west-2
      - CONFIG_PATH=/arxiv/local
    volumes:
      - ./efs/sqlite:/mnt/sqlite
    depends_on:
      - localstack

  db-init:
    build:
      context: ../services/db_init
      dockerfile: Dockerfile
    profiles: ["db", "all"]
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-west-2
      - CONFIG_PATH=/arxiv/local
    volumes:
      - ./efs/sqlite:/mnt/sqlite
    depends_on:
      - localstack

  nvd-checker:
    build:
      context: ../services/nvd_checker
      dockerfile: Dockerfile
    profiles: ["nvd", "all"]
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-west-2
      - CONFIG_PATH=/arxiv/local
    volumes:
      - ./efs/sqlite:/mnt/sqlite
    depends_on:
      - localstack

volumes:
  localstack-data:
