version: '3.8'

services:
  localstack:
    environment:
      - SERVICES=s3,efs,ssm,ses,lambda,logs,iam
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/test/data
      - DEBUG=1

  arxiv-processor:
    environment:
      - CONFIG_PATH=/arxiv/test
      - PYTHONPATH=/app/src
      - TESTING=true
    volumes:
      - ./efs/sqlite-test:/mnt/sqlite
      - ../services/arxiv_processor/tests:/app/tests
    command: pytest /app/tests -v

  db-init:
    environment:
      - CONFIG_PATH=/arxiv/test
      - PYTHONPATH=/app/src
      - TESTING=true
    volumes:
      - ./efs/sqlite-test:/mnt/sqlite
      - ../services/db_init/tests:/app/tests
    command: pytest /app/tests -v

  nvd-checker:
    environment:
      - CONFIG_PATH=/arxiv/test
      - PYTHONPATH=/app/src
      - TESTING=true
    volumes:
      - ./efs/sqlite-test:/mnt/sqlite
      - ../services/nvd_checker/tests:/app/tests
    command: pytest /app/tests -v
