apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: atomiklabs-cluster
  region: us-east-1
  version: "1.28"
iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    availabilityZones: ["us-east-1a"]
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 50