AWSTemplateFormatVersion: "2010-09-09"
Description: "Containerization Infrastructure"

Parameters:
  EnvironmentName:
    Type: String
    Description: "The name of the environment"
    Default: "dev"
    AllowedValues:
      - "test"
      - "dev"
      - "stage"
      - "prod"

Resources:
  ALECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "atomiklabs-ecr-${EnvironmentName}"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: IMMUTABLE
      LifecyclePolicy:
           LifecyclePolicyText: |
              {
                "rules": [
                  {
                    "rulePriority": 1,
                    "description": "Expire images older than 14 days",
                    "selection": {
                      "tagStatus": "untagged",
                      "countType": "sinceImagePushed",
                      "countUnit": "days",
                      "countNumber": 14
                    },
                    "action": {
                      "type": "expire"
                    }
                  }
                ]
              }
  ALECRAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:GetAuthorizationToken
            Resource: "*"

Outputs:
  ECRRepositoryARN:
    Description: "ARN of the ECR Repository"
    Value: !GetAtt ALECRRepository.Arn
    Export:
      Name: "ALECRRepositoryARN"
  ECRRepositoryName:
    Description: "Name of the ECR Repository"
    Value: !Ref ALECRRepository
    Export:
      Name: !Sub "${AWS::StackName}-ECRRepositoryName"
  ECRRepositoryURI:
    Description: "URI of the ECR Repository"
    Value: !GetAtt ALECRRepository.RepositoryUri
    Export:
      Name: "ALECRRepositoryURI"
  ECRAccessPolicyARN:
    Description: "ARN of the IAM Policy for ECR Access"
    Value: !Ref ALECRAccessPolicy
    Export:
      Name: "ALECRAccessPolicyARN"