AWSTemplateFormatVersion: "2010-09-09"
Description: "AtomikLabs Data Persistence Substack Definition"

Parameters:
    DataBucket:
        Type: String
        Description: "The name of the s3 data bucket"
    EnvironmentName:
        Type: String
        Description: "The name of the environment"
        Default: "dev"
        AllowedValues:
            - "test"
            - "dev"
            - "stage"
            - "prod"
    LambdaExecutionRoleArn:
        Type: String
        Description: "The name of the lambda execution role"

Resources:
    DataPersistenceArxivSummaryPersister:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Sub "data-persistence-arxiv-summary-persister-${EnvironmentName}"
            Runtime: python3.9
            Handler: arxiv_summary_persister.lambda_handler
            Code:
                S3Bucket: atomiklabs-iac
                S3Key: code/placeholders/arxiv_summary_persister.zip
            Role: !Ref LambdaExecutionRoleArn
            Timeout: 900
            Environment:
                Variables:
                    DATA_BUCKET: !Ref DataBucket
                    ENVIRONMENT_NAME: !Ref EnvironmentName
                    LOG_LEVEL: INFO
