AWSTemplateFormatVersion: "2010-09-09"
Description: "AtomikLabs Data Ingestion Substack Definition"

Parameters:
    DataBucket:
        Type: String
        Description: "The name of the s3 data bucket"
    EnvironmentName:
        Type: String
        Description: "The name of the environment"
        Default: "dev"
        AllowedValues:
            - "test"
            - "dev"
            - "stage"
            - "prod"
    LambdaExecutionRoleArn:
        Type: String
        Description: "The name of the lambda execution role"

Resources:
    FetchDailySummaries:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Sub "fetch-daily-summaries-${EnvironmentName}"
            Runtime: python3.9
            Handler: fetch_daily_summaries.lambda_handler
            Code:
                S3Bucket: atomiklabs-iac
                S3Key: code/placeholders/fetch-daily-summaries.zip
            Role: !Ref LambdaExecutionRoleArn
            Timeout: 900
            Environment:
                Variables:
                    DATA_BUCKET: !Ref DataBucket
                    ENVIRONMENT_NAME: !Ref EnvironmentName
                    LOG_LEVEL: INFO
    FetchDailySummariesEventRule:
        Type: AWS::Events::Rule
        Properties:
            Name: !Sub "fetch-daily-summaries-rule-${EnvironmentName}"
            Description: "Event rule for triggering the arxiv daily fetch lambda"
            ScheduleExpression: "cron(0 3 * * ? *)"
            State: "ENABLED"
            Targets:
                - Arn: !GetAtt FetchDailySummaries.Arn
                  Id: !Sub "fetch-daily-summaries-event-rule-target-${EnvironmentName}"
    FetchDailySummariesEventRulePermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: "lambda:InvokeFunction"
            FunctionName: !Ref FetchDailySummaries
            Principal: "events.amazonaws.com"
            SourceArn: !GetAtt FetchDailySummariesEventRule.Arn
