AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambdas Stack for AtomikLabs."

Parameters:
  LambdaExecutionRoleArn:
    Type: String
    Description: "ARN of the Lambda Execution Role"
  EnvironmentName:
    Type: String
    Description: "The deployment environment (e.g., dev, test, stage, prod)"
  ECRRepositoryName:
    Type: String
    Description: "Name of the ECR Repository"
  AWSRegion:
    Type: String
    Description: "AWS Region where the ECR repository is located"

Resources:
  FetchDailySummaries:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "fetch-daily-summaries-${EnvironmentName}"
      PackageType: Image
      Role: !Ref LambdaExecutionRoleArn
      MemorySize: 128
      Timeout: 900
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${ECRRepositoryName}:placeholder"

  FetchDailySummariesEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger Fetch Daily Summaries Lambda Function daily at 3 AM"
      ScheduleExpression: "cron(0 3 * * ? *)"
      State: "ENABLED"
      Targets:
        - Id: "FetchDailySummariesTarget"
          Arn: !GetAtt FetchDailySummaries.Arn
          Input: "{}"

  ParseArxivSummaries:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "parse-arxiv-summaries-${EnvironmentName}"
      PackageType: Image
      Role: !Ref LambdaExecutionRoleArn
      MemorySize: 128
      Timeout: 900
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${ECRRepositoryName}:placeholder"
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName
          PERSIST_LAMBDA_FUNCTION_NAME: !Ref PersistArxivSummaries

  PersistArxivSummaries:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "persist-arxiv-summaries-${EnvironmentName}"
      PackageType: Image
      Role: !Ref LambdaExecutionRoleArn
      MemorySize: 128
      Timeout: 900
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWSRegion}.amazonaws.com/${ECRRepositoryName}:placeholder"
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName

  EventBridgePermissionForLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref FetchDailySummaries
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt FetchDailySummariesEventRule.Arn

Outputs:
  FetchDailySummariesFunctionArn:
    Description: "ARN of the Fetch Daily Summaries Lambda Function"
    Value: !GetAtt FetchDailySummaries.Arn
  ParseArxivSummariesFunctionArn:
    Description: "ARN of the Parse Arxiv Summaries Lambda Function"
    Value: !GetAtt ParseArxivSummaries.Arn
  PersistArxivSummariesFunctionArn:
    Description: "ARN of the Persist Arxiv Summaries Lambda Function"
    Value: !GetAtt PersistArxivSummaries.Arn
