AWSTemplateFormatVersion: "2010-09-09"
Description: "AtomikLabs Publishing Substack Definition"

Parameters:
    DataBucket:
        Type: String
        Description: "The name of the s3 data bucket"
    EnvironmentName:
        Type: String
        Description: "The name of the environment"
        Default: "dev"
        AllowedValues:
            - "test"
            - "dev"
            - "stage"
            - "prod"
    LambdaExecutionRoleArn:
        Type: String
        Description: "The name of the lambda execution role"

Resources:
    PublishingPublishingScheduler:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Sub "publishing-publishing-scheduler-${EnvironmentName}"
            Runtime: python3.9
            Handler: publishing_scheduler.lambda_handler
            Code:
                S3Bucket: atomiklabs-iac
                S3Key: code/placeholders/publishing_scheduler.zip
            Role: !Ref LambdaExecutionRoleArn
            Timeout: 900
            Environment:
                Variables:
                    DATA_BUCKET: !Ref DataBucket
                    ENVIRONMENT_NAME: !Ref EnvironmentName
                    LOG_LEVEL: INFO
    PublishingTtsScriptProcessor:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Sub "publishing-tts-script-processor-${EnvironmentName}"
            Runtime: python3.9
            Handler: tts_script_processor.lambda_handler
            Code:
                S3Bucket: atomiklabs-iac
                S3Key: code/placeholders/tts_script_processor.zip
            Role: !Ref LambdaExecutionRoleArn
            Timeout: 900
            Environment:
                Variables:
                    DATA_BUCKET: !Ref DataBucket
                    ENVIRONMENT_NAME: !Ref EnvironmentName
                    LOG_LEVEL: INFO
    PublishingTtsScriptCreator:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Sub "publishing-tts-script-creator-${EnvironmentName}"
            Runtime: python3.9
            Handler: tts_script_creator.lambda_handler
            Code:
                S3Bucket: atomiklabs-iac
                S3Key: code/placeholders/tts_script_creator.zip
            Role: !Ref LambdaExecutionRoleArn
            Timeout: 900
            Environment:
                Variables:
                    DATA_BUCKET: !Ref DataBucket
                    ENVIRONMENT_NAME: !Ref EnvironmentName
                    LOG_LEVEL: INFO
    PublishingNewsletterCreator:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: !Sub "publishing-newsletter-creator-${EnvironmentName}"
            Runtime: python3.9
            Handler: newsletter_creator.lambda_handler
            Code:
                S3Bucket: atomiklabs-iac
                S3Key: code/placeholders/newsletter_creator.zip
            Role: !Ref LambdaExecutionRoleArn
            Timeout: 900
            Environment:
                Variables:
                    DATA_BUCKET: !Ref DataBucket
                    ENVIRONMENT_NAME: !Ref EnvironmentName
                    LOG_LEVEL: INFO
