AWSTemplateFormatVersion: "2010-09-09"
Description: "AtomikLabs Data Layer Substack Definitions"

Parameters:
  EnvironmentName:
    Type: String
    Description: "The name of the environment"
    Default: "dev"
    AllowedValues:
      - "dev"
      - "stage"
      - "prod"

Resources:
  AtomikLabsLogsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "atomiklabs-logs"

  AtomikLabsDataBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "atomiklabs-data-bucket-${EnvironmentName}"
      LifecycleConfiguration:
        Rules:
          - Id: "MoveToIAAfterOneWeek"
            Status: "Enabled"
            Transitions:
              - TransitionInDays: 31
                StorageClass: "STANDARD_IA"
      LoggingConfiguration:
        DestinationBucketName: !Sub "atomiklabs-logs"
        LogFilePrefix: "data-bucket-logs/${EnvironmentName}/"

Outputs:
  S3BucketName:
    Description: "Name of the S3 Bucket for Data Layer"
    Value: !Ref AtomikLabsDataBucket