name: AWS Validate CloudFormation

on:
    pull_request:
        branches:
            - main
            - dev
            - stage
        paths:
            - "**/*.yaml"
            - "**/*.yml"

jobs:
    aws-validate:
        name: Validate CloudFormation Templates
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Validate CloudFormation YAML templates
              run: |
                  run: |
                    find . -name '*.yaml' -not -path "./.github/*" -or -name '*.yml' -not -path "./.github/*" | while read -r template; do
                      echo "Validating $template"
                      aws cloudformation validate-template --template-body file://"$template" || exit 1
                    done
