name: Infra

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

permissions:
      id-token: write
      contents: read
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity