name: Lint and Validate

on:
    push:
        branches:
            - main
            - dev
            - stage
            - feature/*
        paths:
            - "**/*.yaml"
            - "**/*.yml"

jobs:
    lint-and-validate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.x"

            - name: Install cfn-lint
              run: pip install cfn-lint

            - name: Lint CloudFormation templates
              run: cfn-lint -t ./**/*.yaml ./**/*.yml

            - name: Validate CloudFormation templates
              run: |
                  for template in $(find . -name '*.yaml' -or -name '*.yml'); do
                    aws cloudformation validate-template --template-body file://$template
                  done
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: ${{ secrets.AWS_REGION }}
