name: Python Lint and Format

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Flake8
        run: pip install flake8

      - name: Get Changed Files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4

      - name: Lint Changed Python Projects
        run: |
          CHANGED_FILES="${{ steps.files.outputs.all }}"
          CHANGED_DIRS=$(echo "$CHANGED_FILES" | xargs -n 1 dirname | sort -u)
          for dir in $CHANGED_DIRS; do
            if [[ -f "$dir/requirements.txt" ]]; then
              echo "Linting $dir"
              flake8 $dir
            fi
          done
