name: Python Services Tests

on:
  pull_request:
    paths:
      - 'services/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies and run tests
      run: |
        for service in services/*; do
          if [ -d "$service" ]; then
            echo "Running tests in $service"
            pip install -r $service/requirements.txt
            pytest $service/tests
          fi
        done

    - name: Check test coverage
      run: |
        coverage run -m pytest services/fetch_daily_summaries/tests/
        coverage report -m --fail-under=80
