name: Python Services Tests

on:
  pull_request:
    paths:
      - 'services/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pytest and Coverage
        run: pip install pytest coverage

      - name: Get Changed Services
        id: get-changed-services
        run: |
          git diff --name-only origin/main ${{ github.head_ref }} | grep 'services/' | cut -d '/' -f 1-2 | uniq > changed_services.txt

      - name: Install dependencies for Changed Services
        run: |
          while read service; do
            if [ -d "$service/src" ]; then
              requirements_path="$service/src/requirements.txt"
              if [ -f "$requirements_path" ]; then
                echo "Installing dependencies for $service"
                pip install -r $requirements_path
              else
                echo "No requirements.txt found in $service/src"
              fi
            fi
          done < changed_services.txt

      - name: Run tests for Changed Services
        run: |
          while read service; do
            if [ -d "$service/tests" ]; then
              echo "Running tests in $service"
              pytest $service/tests
            fi
          done < changed_services.txt

      - name: Check test coverage
        run: |
          while read service; do
            if [ -d "$service/tests" ]; then
              coverage run -m pytest $service/tests
            fi
          done < changed_services.txt
          coverage report -m --fail-under=80
