name: Python Services Tests

on:
  pull_request:
    paths:
      - 'services/**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get Changed Services
        id: get-changed-services
        run: |
          echo "Changed services:" > changed_services.txt
          for file in $(git diff --name-only origin/main ${{ github.head_ref }} | grep 'services/'); do
            dirname $file | cut -d '/' -f 1-2 | uniq >> changed_services.txt
          done
          echo "CHANGED_SERVICES=$(cat changed_services.txt | uniq)" >> $GITHUB_ENV

      - name: Install dependencies and run tests for Changed Services
        run: |
          pip install coverage pytest
          for service in $(cat changed_services.txt | uniq); do
            if [ -d "$service/src" ]; then
              requirements_path="$service/src/requirements.txt"
              if [ -f "$requirements_path" ]; then
                echo "Running tests in $service"
                pip install -r $requirements_path
                pytest $service/tests
              else
                echo "No requirements.txt found in $service/src"
              fi
            fi
          done

      - name: Check test coverage
        run: |
          coverage run -m pytest $(cat changed_services.txt | sed 's|$|/tests|')
          coverage report -m --fail-under=80
